DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS content;
DROP TABLE IF EXISTS post;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE content (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  content_title TEXT NOT NULL,
  content TEXT NOT NULL
);